FROM eyedeekay/lede-docker

USER lede-build
RUN make V=s defconfig

COPY .config.in.wndr3800 /home/lede-build/source/.config
USER root

RUN chown lede-build:lede-build /home/lede-build/source/.config
USER lede-build

RUN make defconfig
RUN make -j3 V=s
CMD bash
