FROM eyedeekay/lede-docker
USER lede-build

COPY .config.in.mtseeed /home/lede-build/source/.config

USER root
RUN chown lede-build:lede-build /home/lede-build/source/.config

USER lede-build
RUN make defconfig

CMD make
