FROM eyedeekay/lede-docker
USER lede-build

COPY .config.in.omega2 /home/lede-build/source/.config

USER root
RUN chown lede-build:lede-build /home/lede-build/source/.config

USER lede-build
RUN git clone https://github.com/eyedeekay/omega2-files files
RUN make defconfig

RUN make V=s

CMD make V=s
